// Entry point for wrangler (see wrangler.toml `main`). Wraps the worker generated by
// `opennextjs-cloudflare build` and is excluded from the Next typecheck.
// @ts-expect-error: generated at build time
import { default as openNextWorker } from "./.open-next/worker.js";

type Ctx = { waitUntil(promise: Promise<unknown>): void };

const worker = {
    async fetch(request: Request, env: unknown, ctx: Ctx): Promise<Response> {
        const url = new URL(request.url);
        // Route handlers under /api run on every request; a Worker's own responses never
        // reach Cloudflare's CDN cache, so store them in this data center's Cache API.
        const edgeCacheable = request.method === "GET" && url.pathname.startsWith("/api/");
        const cache = (caches as unknown as { default: Cache }).default;

        if (edgeCacheable) {
            const hit = await cache.match(request);
            if (hit) return hit;
        }

        const response: Response = await openNextWorker.fetch(request, env, ctx);

        // Next adds s-maxage to 404s from ISR routes and there's no setting to turn it off.
        // Errors must never be stored by a browser or CDN.
        if (response.status >= 400) {
            const headers = new Headers(response.headers);
            headers.set("Cache-Control", "no-store");
            return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
        }

        if (edgeCacheable && response.status === 200 && /s-maxage=\d+/.test(response.headers.get("Cache-Control") || "")) {
            // Buffer instead of response.clone(): API bodies are small JSON, and a tee'd
            // stream stalls the client response until cache.put finishes reading.
            const body = await response.arrayBuffer();
            const init = { status: response.status, statusText: response.statusText, headers: response.headers };
            ctx.waitUntil(cache.put(request, new Response(body, init)));
            return new Response(body, init);
        }
        return response;
    },
};

export default worker;
