"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { Activity, ArrowLeft, BarChart2, Percent, Plus, RefreshCw, Search, TrendingUp, Users } from 'lucide-react';
import { MotionDiv } from "@/components/layout/Motion";

export default function ReferralAnalyticsClient() {
    const [clicks, setClicks] = useState(120);
    const [signups, setSignups] = useState(48);

    // K-Factor calculation: Average number of new users generated by each existing user.
    // In our simplified loop: K = (signups / active referrers)
    // Let's assume there are 30 active referrers.
    const activeReferrers = 30;
    const kFactor = parseFloat((signups / activeReferrers).toFixed(2));

    const conversionRate = parseFloat(((signups / clicks) * 100).toFixed(1));

    const handleAddClicks = () => {
        setClicks(prev => prev + 10);
    };

    const handleAddSignup = () => {
        setSignups(prev => prev + 1);
        setClicks(prev => prev + 1); // A signup must originate from a click
    };

    const handleReset = () => {
        setClicks(120);
        setSignups(48);
    };

    // Simulated referral sources
    const referralSources = [
        { name: "WhatsApp Chat", share: 45, count: Math.round(signups * 0.45) },
        { name: "Twitter/X Feed", share: 30, count: Math.round(signups * 0.30) },
        { name: "Telegram Groups", share: 15, count: Math.round(signups * 0.15) },
        { name: "Direct Messages", share: 10, count: Math.round(signups * 0.10) },
    ];

    // Simulated Search Console keyword performance data
    const keywordData = [
        { query: "fmovies alternative 2026", clicks: 1240, impressions: 8500, ctr: "14.5%", pos: 1.2 },
        { query: "best free movie streaming sites no sign up", clicks: 980, impressions: 7200, ctr: "13.6%", pos: 2.1 },
        { query: "free movie websites with referral program", clicks: 430, impressions: 3100, ctr: "13.8%", pos: 1.5 },
        { query: "watch movies free no sign up required", clicks: 310, impressions: 5600, ctr: "5.5%", pos: 4.8 },
    ];

    return (
        <main className="min-h-screen bg-black text-neutral-300 py-32 px-6 md:px-16 lg:px-24 relative overflow-hidden">
            {/* Glowing accents */}
            <div className="absolute top-1/4 left-1/4 w-96 h-96 rounded-full bg-red-600/5 blur-[100px] pointer-events-none" />
            <div className="absolute bottom-1/4 right-1/4 w-96 h-96 rounded-full bg-rose-600/10 blur-[120px] pointer-events-none" />

            <div className="max-w-5xl mx-auto relative z-10">
                {/* Back link */}
                <Link href="/referral" className="inline-flex items-center gap-2 text-sm font-bold text-red-500 hover:text-white transition-colors mb-8">
                    <ArrowLeft size={16} /> Back to Referrals
                </Link>

                {/* Hero Header */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
                    <div>
                        <h1 className="text-3xl md:text-5xl font-black text-white tracking-tighter mb-2">
                            Referral & Growth Analytics
                        </h1>
                        <p className="text-neutral-400 text-sm md:text-base">
                            Track the viral coefficient loop (K-Factor) and search visibility performance in real-time.
                        </p>
                    </div>

                    {/* Simulation Panel */}
                    <div className="flex flex-wrap gap-2 items-center rounded-2xl border border-white/5 bg-white/[0.02] p-2 backdrop-blur-md">
                        <button
                            onClick={handleAddClicks}
                            className="flex items-center gap-1.5 rounded-xl bg-white/5 hover:bg-white/10 px-3 py-2 text-xs font-bold text-white transition-all active:scale-95 cursor-pointer"
                        >
                            <Plus size={14} /> Add 10 Clicks
                        </button>
                        <button
                            onClick={handleAddSignup}
                            className="flex items-center gap-1.5 rounded-xl bg-red-600 hover:bg-red-700 px-3 py-2 text-xs font-bold text-white transition-all active:scale-95 cursor-pointer shadow-lg shadow-red-600/10"
                        >
                            <Plus size={14} /> Add Signup
                        </button>
                        <button
                            onClick={handleReset}
                            className="rounded-xl border border-white/5 p-2 text-neutral-500 hover:text-white transition-colors cursor-pointer"
                            title="Reset Simulation"
                        >
                            <RefreshCw size={14} />
                        </button>
                    </div>
                </div>

                {/* Scorecard Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
                    {[
                        { title: "Total Clicks", value: clicks, icon: Activity, detail: "Total visits on referral links" },
                        { title: "Success Signups", value: signups, icon: Users, detail: "New cohort registrations" },
                        { title: "Conversion Rate", value: `${conversionRate}%`, icon: Percent, detail: "Click to signup ratio" },
                        { 
                            title: "Loop K-Factor", 
                            value: kFactor, 
                            icon: TrendingUp, 
                            detail: "Viral loops (>1.0 indicates exponential growth)", 
                            highlight: kFactor >= 1.0 ? "text-green-400 font-black drop-shadow-[0_0_12px_rgba(74,222,128,0.3)]" : "text-amber-500 font-bold"
                        },
                    ].map((stat, idx) => (
                        <div key={idx} className="rounded-2xl border border-white/[0.06] bg-neutral-950/80 p-5 backdrop-blur-xl">
                            <div className="flex items-center justify-between mb-4">
                                <span className="text-xs font-bold text-neutral-500 uppercase tracking-wider">{stat.title}</span>
                                <stat.icon className="h-4 w-4 text-neutral-400" />
                            </div>
                            <div className={`text-2xl md:text-3xl font-black mb-1 ${stat.highlight || "text-white"}`}>
                                {stat.value}
                            </div>
                            <p className="text-[10px] text-neutral-500 leading-relaxed">{stat.detail}</p>
                        </div>
                    ))}
                </div>

                {/* Main Content Sections: Sources & Search Analytics */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    {/* Left: Traffic Channels (1 column) */}
                    <div className="rounded-3xl border border-white/[0.08] bg-neutral-950/80 p-6 backdrop-blur-xl">
                        <div className="flex items-center gap-2 mb-6">
                            <BarChart2 className="h-5 w-5 text-red-500" />
                            <h2 className="text-lg font-bold text-white">Share of Referral traffic</h2>
                        </div>
                        
                        <div className="space-y-6">
                            {referralSources.map((source, idx) => (
                                <div key={idx} className="space-y-2">
                                    <div className="flex justify-between text-xs">
                                        <span className="font-bold text-neutral-300">{source.name}</span>
                                        <span className="text-neutral-500 font-black">{source.count} signups ({source.share}%)</span>
                                    </div>
                                    <div className="h-2 w-full rounded-full bg-white/5 overflow-hidden">
                                        <div 
                                            className="h-full bg-gradient-to-r from-red-600 to-rose-500 rounded-full transition-all duration-500"
                                            style={{ width: `${source.share}%` }}
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Right: Search Console Rankings (2 columns) */}
                    <div className="lg:col-span-2 rounded-3xl border border-white/[0.08] bg-neutral-950/80 p-6 backdrop-blur-xl">
                        <div className="flex items-center gap-2 mb-6">
                            <Search className="h-5 w-5 text-red-500" />
                            <h2 className="text-lg font-bold text-white">AEO / Search Performance (GSC)</h2>
                        </div>

                        <div className="overflow-x-auto">
                            <table className="w-full text-left border-collapse text-xs md:text-sm">
                                <thead>
                                    <tr className="border-b border-white/[0.08] text-neutral-500 font-bold">
                                        <th className="pb-3">Keyword Query</th>
                                        <th className="pb-3 text-right">Clicks</th>
                                        <th className="pb-3 text-right">Impressions</th>
                                        <th className="pb-3 text-right">CTR</th>
                                        <th className="pb-3 text-right">Position</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {keywordData.map((kw, idx) => (
                                        <tr key={idx} className="border-b border-white/5 hover:bg-white/[0.01] transition-colors">
                                            <td className="py-3.5 font-bold text-white">{kw.query}</td>
                                            <td className="py-3.5 text-right text-neutral-300">{kw.clicks}</td>
                                            <td className="py-3.5 text-right text-neutral-400">{kw.impressions}</td>
                                            <td className="py-3.5 text-right text-rose-500 font-bold">{kw.ctr}</td>
                                            <td className="py-3.5 text-right text-neutral-300 font-bold">{kw.pos}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                {/* Context Tip */}
                <div className="mt-8 rounded-2xl border border-red-500/10 bg-red-500/5 p-4 flex gap-3 items-start">
                    <TrendingUp className="h-5 w-5 text-red-500 shrink-0 mt-0.5" />
                    <div>
                        <h4 className="text-xs font-bold text-white mb-1">Growth Hacking Analytics Tip</h4>
                        <p className="text-[11px] text-neutral-400 leading-relaxed">
                            A K-Factor above 1.0 represents exponential growth: each new cohort of users successfully refers more than 1 new subscriber. Monitor referral channels and prioritize high-conversion sharing actions (like WhatsApp) to push K-Factor beyond the viral threshold.
                        </p>
                    </div>
                </div>
            </div>
        </main>
    );
}
